name: Java CI with Gradle

on:
  push:
    branches: [ main, testng, junit4 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получение кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Java 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      # Шаг 3: Даем права на выполнение gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Шаг 4: Сборка проекта
      - name: Build with Gradle
        run: ./gradlew build

      # Шаг 5: Запуск тестов
      - name: Run tests
        run: ./gradlew test